### ISSUE TITLE
Chrome says extension can see history, install did not state this

### ISSUE THREAD

**Issue by givihuda** [itsHobbes/div-highlighter#2]
I'm commenting on your comment from here (in a new issue because you closed the previous one because I didn't notice or reply to your reply in a time period that you preferred):

https://github.com/itsHobbes/div-highlighter/issues/1#issuecomment-845836161

I gave details but apparently not enough.

The Chrome extension page - https://chrome.google.com/webstore/detail/div-highlighter/facdmpkhcadnpcpeodngcnjjmgapfjia?hl=en-GB - and install doesn't state that it can read browsing history, but after install, Chrome's Manage Extensions page for it says it can:

![image](https://user-images.githubusercontent.com/74785256/121217805-6d77e180-c83f-11eb-981f-f5457724083c.png)

Per the previous issue, to address your statements, I did a normal install, just like with any other extension (I don't think I need to describe those steps as you're already aware of how that works). After install, I did the normal thing any user would do, and tried to click the extension at the top right of the address bar... it then disappeared. 

When I went to Manage Extensions, and clicked into the Details for it, that's where it showed it can read history.

So if you're telling me that it doesn't read history, why is Chrome telling me that it does?

**Comment by givihuda** [comment]
Also the 2nd issue has come back... the extension just disappears from the toolbar (which means there's nothing to click) even though it's "On" and even while it's set to be available on all pages. 

So I'm completely confused on why the extension button just seems to randomly disappear. I've yet to see it return too, it's only shown right after install.

This time however I saw what it would do when I click it, but when I clicked outside of the box to type up this issue, it disappeared and hasn't come back. Is it crashing? I know that Chrome will close an extension if it's incompatible or runs a line of code that doesn't work for some reason, but I can't tell what's going on here. My Chrome auto-updates.

**Comment by itsHobbes** [comment]
@givihuda So this "Read your browsing history" seems like an all encompassing phrase from google. As I said in the previous issue, it does not, and cannot read your actual history. The extension simply needs access to the *current* browser page so that it can modify the div colours. I don't know why chrome does this, but the source code is there, it does not read your browser history.

Chrome extensions get hidden on the bar by default, you need to "pin" them for them to stick around up there. See my screenshot, I don't have it pinned and it does not show in the bar. But the extensions I do have pinned, do show up in the bar. Click the jigsaw piece then click the pin icon to pin/unpin

![image](https://user-images.githubusercontent.com/10854475/121231004-c9feef00-c887-11eb-92a4-be758e71f079.png)

**Comment by givihuda** [comment]
> So this "Read your browsing history" seems like an all encompassing phrase from google. As I said in the previous issue, it does not, and cannot read your actual history.

Who am I supposed to believe here 😆 Google or the extension developer?!

I notice below that it also says "Warning: Google Chrome cannot prevent extensions from recording your browsing history."

I realize that that's stated inside of the "Allow in Incognito" setting, but the setting is only to allow the extension to run in Incognito, which of course is a different ability than being able to read my browsing history, which Chrome is telling me it can't prevent an extension from doing (presumably because of Permission "Read your browsing history", whether that's always on by Chrome or a default in extensions unless explicitly turned off by you the developer).

So while I understand that your source code doesn't explicitly request permission to history, or try to fetch it or send it somewhere, maybe there's something we're not understanding with Chrome extensions here? My concern is that with Chrome stating it has permission, an auto-update to any extension with this permission could suddenly have to the ability to send my history to the developer... this may completely be a Google/Chrome design flaw, but it's still a concern. 

Anyway, while I don't think you're malicious, if there's a way in your code or something to disable history permission or gathering so that Chrome realizes the extension is not going to use my browsing history, that would alleviate my concern. If that's not possible or feasible, then oh well, it's a coin toss on whether I use the extension, but please don't take it personally or get upset over any of my comments here. I will just note that I've had trustworthy extensions turn malicious after being sold to another developer... so you can understand where I'm coming from.

> Chrome extensions get hidden on the bar by default

Thanks for the clarification. It's been a while since I've used extensions (partly because of some malicious experiences with previously-trustworthy ones), so this behavior is new to me (the opposite of how it used to be, where they were "pinned" by default). So I'll look into this.

If there's any pressure you can provide to Google to "fix" their stated history permissions (if you're doing things right), that would probably be more valuable than me pressuring them. Please feel free to use my threads in any posts to their developer boards or email to their team, as I think this is a real security concern for users and extension developers alike.

Thanks for your patience and understanding.
